const ExperienceActionTypes = {
  FETCH_EXPERIENCE_START: 'FETCH_EXPERIENCE_START',
  FETCH_EXPERIENCE_FAILURE: 'FETCH_EXPERIENCE_FAILURE',
  FETCH_EXPERIENCE_SUCCESSS: 'FETCH_EXPERIENCE_SUCCESSS'
}

export default ExperienceActionTypes;