const ProjectActionTypes = {
  ADD_PROJECT: 'ADD_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',

  FETCH_PROJECTS_START: 'FETCH_PROJECTS_START',
  FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_FAILURE',
  FETCH_PROJECTS_SUCCESSS: 'FETCH_PROJECTS_SUCCESSS'
}

export default ProjectActionTypes;