const SkillActionTypes = {
  FETCH_SKILLS_START: 'FETCH_SKILLS_START',
  FETCH_SKILLS_FAILURE: 'FETCH_SKILLS_FAILURE',
  FETCH_SKILLS_SUCCESS: 'FETCH_SKILLS_SUCCESS'
}

export default SkillActionTypes;